name: Post-deployment validation.

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Target resource group name'
        required: true
        default: 'az-test-storage-rg'
        type: string
      storageAccountName:
        description: 'Name of the storage account'
        required: true
        default: 'aztststg005'
        type: string

permissions:
  id-token: write
  contents: read

env:
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_LOCATION: "westeurope"

jobs:
  validate-pester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repo
        id: checkout
        with:
          fetch-depth: 0

      - uses: azure/login@v1
        name: Sign in to Azure
        id: login
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Pester tests
        id: pester
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Import-Module Pester -Force
            $configuration = [PesterConfiguration]::Default
            $configuration.TestResult.Enabled = $true
            $configuration.Output.Verbosity = 'Detailed'
            $configuration.Output.CIFormat = 'GithubActions'
            $container = New-PesterContainer -Path "./tests/*.tests.ps1" -Data @{ subId = "${{ env.ARM_SUBSCRIPTION_ID }}"; ResourceGroupName = "${{ env.RESOURCE_GROUP }}"; StorageAccountName = "${{ env.STORAGE_ACCOUNT }}" }
            $configuration.Run.Container = $container
            $configuration.Run.PassThru = $true
            $result = Invoke-Pester -Configuration $configuration
            exit $result.FailedCount
          azPSVersion: "latest"
        env:
          RESOURCE_GROUP: ${{ inputs.resourceGroupName }}
          STORAGE_ACCOUNT: ${{ inputs.storageAccountName }}
